language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev libqt5webkit5-dev libdbus-1-dev jsdoc-toolkit
script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
